const genres: string[] = [
  "JUVENILE FICTION",
  "Young Adult Fiction",
  "Juvenile Fiction",
  "Fiction",
  "History",
  "Photography",
  "Boys in literature",
  "American fiction",
  "American wit and humor",
  "Pictorial",
  "Atmospheric carbon dioxide",
  "Social Science",
  "Philosophy",
  "Science",
  "Biography & Autobiography",
  "Nature",
  "Art",
  "Cooking",
  "Badlands (S.D. and Neb.)",
  "Travel",
  "Authors",
  "English",
  "Arabian Peninsula",
  "American drama",
  "Arab countries",
  "American poetry",
  "Christianisme et politique",
  "Cities and towns",
  "Political Science",
  "Kidnapping victims",
  "Detective and mystery stories",
  "Religion",
  "Great Britain",
  "Cambridge (England)",
  "Literary Criticism",
  "Juvenile Nonfiction",
  "Laguna Indians",
  "Gardening",
  "Reference",
  "Cows",
  "Business & Economics",
  "Australian fiction",
  "Readers (Primary)",
  "Children's stories",
  "Beginner reader",
  "Brisbane (Qld.)",
  "Body",
  "Mind & Spirit",
  "Health & Fitness",
  "Male homosexuality",
  "Performing Arts",
  "Modern",
  "Cookery",
  "Drama",
  "United States",
  "Canadian drama",
  "Poetry",
  "Canadian fiction",
  "Sports & Recreation",
  "Fishing",
  "Domestic fiction",
  "Families",
  "Cold War",
  "BIOGRAPHY & AUTOBIOGRAPHY",
  "Comics & Graphic Novels",
  "American",
  "Ghost stories",
  "Fairy tales.",
  "Fantasy fiction",
  "Medical",
  "Human",
  "Anesthesia",
  "Education",
  "Family & Relationships",
  "Actors",
  "Alaska",
  "Absentee fathers",
  "English drama",
  "September 11 Terrorist Attacks",
  "Language Arts & Disciplines",
  "Organizational change",
  "Computers",
  "Arctic regions",
  "Canadian poetry",
  "Poetics",
  "Comic books",
  "strips",
  "etc",
  "Humor",
  "Alternative comic books",
  "Ackroyd",
  "Roger (Fictitious character)",
  "Children's poetry",
  "New Zealand",
  "Children",
  "Liberty",
  "Literary Collections",
  "Foreign Language Study",
  "Electronic books",
  "English language",
  "Child rearing",
  "COMICS & GRAPHIC NOVELS",
  "Birthdays",
  "Japanese fiction",
  "Ethnic neighborhoods",
  "Courts",
  "American literature",
  "Young Adult Nonfiction",
  "California",
  "Monsters",
  "Historical fiction",
  "Brothers",
  "FICTION",
  "Emperors",
  "Alienation (Social psychology)",
  "Architects",
  "Adventure stories",
  "Biographical fiction",
  "Canadian (English)",
  "Short stories",
  "Canadian",
  "Mennonites",
  "Alberta",
  "Landscape photography",
  "Crime and criminals",
  "True Crime",
  "FAMILY & RELATIONSHIPS",
  "Abenaki Indians",
  "Finance",
  "Runaway teenagers",
  "Electronic surveillance",
  "Dams",
  "CD-ROMs",
  "Personal",
  "Canada",
  "Bank robberies",
  "Boxing",
  "Caricatures and cartoons",
  "College stories",
  "Adultery",
  "Family secrets",
  "Murder for hire",
  "African Americans",
  "Psychology",
  "Grief",
  "Europe",
  "Eastern",
  "Algerian fiction",
  "Fathers and daughters",
  "Educators",
  "Literature",
  "Bosch",
  "Harry (Fictitious character)",
  "Chipewyan Indians",
  "Arctic Regions",
  "Animal behavior",
  "Caribou Eskimos",
  "Admission of nonimmigrants",
  "Canada (Nord)",
  "Siberia (Russia)",
  "America",
  "Activity programs in education",
  "Friendship in youth",
  "American Life",
  "Individualism",
  "Science fiction",
  "Australian",
  "Scarpetta",
  "Kay (Fictitious character)",
  "Nationalism",
  "Explorers",
  "Arab-Israeli conflict",
  "Israel",
  "Black humor",
  "Canadian literature",
  "Choice (Psychology)",
  "Ability",
  "Good and evil",
  "Boys",
  "Datine (Social customs)",
  "Art appreciation",
  "Latin American fiction",
  "Ethnic conflict",
  "Books and reading",
  "Fantastic fiction",
  "Antiques & Collectibles",
  "Mathematics",
  "Children's rooms",
  "Cold cases (Criminal investigation)",
  "Demonology",
  "Christianity",
  "Africa",
  "Music",
  "Beat generation",
  "Psychological fiction",
  "Indigenous peoples",
  "Cellists",
];

export default genres;
